# Generated by Django 4.2.1 on 2023-06-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_pollsquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollsQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('questiontext', models.CharField(max_length=200)),
                ('createddate', models.DateTimeField()),
                ('objecttype', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'polls_question',
                'managed': False,
            },
        ),
    ]
