# Generated by Django 4.2.1 on 2023-06-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pollsquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loggingchatbot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createddate', models.DateTimeField()),
                ('content', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'loggingchatbot',
                'managed': False,
            },
        ),
    ]
